#!/bin/bash
#

# A git hook script that runs the same checks that are 
# executed on Travis to verify your commits will not fail.
# Bypass it with the --no-verify option to git-commit
#
# usage: make a symlink to this file,
# e.g., rm -rf .git/hooks/ && ln -s -f ../_hooks .git/hooks

# Run 
./_tests/travis-checks.sh --disable-external

if [ $? -eq 0 ]; then
    exit 0
else
  echo "**********************************************************"
  echo -e "*  \033[31mCOMMIT ABORTED! Please address the errors before commiting.\033[0m"
#  echo -e "*  This can be done automatically for each file by using the following command:"
#  echo -e "*  \033[46msed -ie 's/[[:space:]]*$//' <filename>\033[0m"
  echo "**********************************************************"
  echo ""
fi