#!/bin/bash

# A git hook script that runs the same checks that are executed on Travis to
# verify your commits will not fail. Bypass it with the --no-verify option to
# git commit
#
# usage: make a symlink to this file,
# e.g., rm -rf .git/hooks/ && ln -s -f ../_hooks .git/hooks

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

RUN=
if docker inspect --type=image local-website &> /dev/null ; then
  RUN="docker run --rm --volume $PWD:/home/website --tty local-website"
else
  echo "WARNING: building website using local system environment."
  echo "WARNING: use officially supported docker image environment by running:"
  echo "         docker build -t local-website ."
fi
$RUN ./_tests/travis-checks

if [ $? -eq 0 ]; then
  exit 0
else
  err "COMMIT ABORTED! Please address the errors before commiting."
  exit 1
fi
