source 'https://rubygems.org'

require 'open-uri'

gem 'github-pages'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-jupyter-notebook'
gem 'jekyll-paginate'
gem 'json'
gem 'liquid'
gem 'mdl'
gem 'openssl'
gem 'sassc'
gem 'mini_portile2'