#!/bin/bash

set -e

# Execute Markdown Linter
#bundle exec mdl README.md _posts _pages --style _linter/markdown-linter-style.rb

# Github Pages needs the basejs field to be "src/boot.js" in order for the site
# to use the source js, but when we deploy to production, we should set this
# field to one concatenated & minified js file to use on the site.  This
# command replaces "src/boot.js" with "app.js".
sed -e '/^basejs/s/\src\/boot\.js/app\.js/' _config.yml > _config-deploy.yml

# Commnand to concatenate & minify all source javascript into one concatenated
# and minified file optmized for production use.
node js/libs/r.js -o js/app.build.js

# Skips validation checks that take a long time
htmlproofer_args_extra=""
if [ "$1" = "--quick" ]; then
  htmlproofer_args_extra="--disable-external"
fi

# Run HTMLProofer
bundle exec jekyll build --config _config-deploy.yml
#bundle exec htmlproofer ./_site --only-4xx --file-ignore "/ndt/" "$htmlproofer_args_extra"
